# Sample configuration file for Sidekiq.
# Options here can still be overridden by cmd line args.
# Place this file at config/sidekiq.yml and Sidekiq will
# pick it up automatically.

# run with : sidekiq -C config/sidekiq.yml
# stop with : sidekiqctl stop tmp/pids/sidekiq.pid 60
---
:verbose: false
:concurrency: 10
:pidfile: tmp/pids/sidekiq.pid
:daemon: true
:logfile: log/sidekiq.log

# Set timeout to 8 on Heroku, longer if you manage your own systems.
:timeout: 30

# Sidekiq will run this file through ERB when reading it so you can
# even put in dynamic logic, like a host-specific queue.
# http://www.mikeperham.com/2013/11/13/advanced-sidekiq-host-specific-queues/
:queues:
  - critical
  - default
  - mailers

# you can override concurrency based on environment
production:
  :concurrency: 5
staging:
  :concurrency: 2
development:
  :concurrency: 1